import QueryProvider from '@/components/QueryProvider'
import type { Metadata } from 'next'
import { PropsWithChildren, Suspense } from 'react'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={null}>
          <QueryProvider>{props.children}</QueryProvider>
        </Suspense>
      </body>
    </html>
  )
}
